### ISSUE TITLE
Missing react-native-gesture-handler dependency [only web version]

### ISSUE THREAD

**Issue by CharlieGaynor** [ixartz/React-Native-Boilerplate#4]
After cloning & running npm install, this issue seems to be present

npm run web

> react-native-boilerplate@1.0.0 web
> expo start --web

Starting project at ~/Documents/repos/boilerplate
Starting Metro Bundler
Some dependencies are incompatible with the installed expo version:
  expo-splash-screen@0.20.4 - expected version: ~0.20.5
  react-native-gesture-handler@2.9.0 - expected version: ~2.12.0
Your project may not work correctly until you install the correct versions of the packages.
Fix with: npx expo install --fix
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █   █▄▀▀▄██ ▄▄▄▄▄ █
█ █   █ █ ▀▄ █▀█ ██ █   █ █
█ █▄▄▄█ █▀██▀▀█▀▄██ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄▀▄█ █▄█▄█▄▄▄▄▄▄▄█
█▄ ▀█▄ ▄██▀▀▄▀█▄ ███ ▀▄▄ ▄█
█▀█▀▀ █▄▄ █▀ ▄██ ▀▀ █▄  ▀██
█▀██ ▀▄▄█▀█▄█▄▀▄▀▄▀▄▀▀▄ ▀██
███▄█▄█▄▄  ▄█▀██▄▄▄█▄▀ ▀███
█▄▄█▄█▄▄█ █▀▄▀█▄▄ ▄▄▄ ▀ ▄▄█
█ ▄▄▄▄▄ █▀▄▄ ▄██▀ █▄█ ▀▀█▀█
█ █   █ █▄█▄█▄▀▄█▄▄ ▄▄▀   █
█ █▄▄▄█ █▀▄▄█▀█▀▄██▄▀█▀▀ ██
█▄▄▄▄▄▄▄█▄▄█▄▄▄▄████▄▄▄▄▄▄█

› Metro waiting on exp://192.168.1.48:8081
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Web is waiting on http://localhost:8081

› Using Expo Go
› Press s │ switch to development build

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu
› Press o │ open project code in your editor

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
Web Bundling failed 810ms
Unable to resolve "react-native-web/dist/exports/DrawerLayoutAndroid" from "node_modules/react-native-gesture-handler/lib/module/components/GestureComponents.web.js"

Potentially fixed with npx expo install react-native-gesture-handler

**Comment by ixartz** [comment]
@CharlieGaynor, I was mostly focusing on iOS and Android version. Didn't take the time to test on the web version.

I'm totally open to suggestion.

**Comment by ixartz** [comment]
@CharlieGaynor I'm a little busy right now, if you have any idea to solve the issue I'm totally open to suggestions and insights.
