### ISSUE TITLE
Nativewind styling not applied on the web

### ISSUE THREAD

**Issue by CharlieGaynor** [ixartz/React-Native-Boilerplate#5]
I believe it's related to this issue here https://github.com/marklawlor/nativewind/issues/470, but out of the box, the nativewind styling is not applied on the web.

Adding import { NativeWindStyleSheet } from "nativewind";

NativeWindStyleSheet.setOutput({
  default: "native",
});

to the _layout.tsx seems to fix this, but I'm not sure if this the proper solution

**Comment by ixartz** [comment]
@CharlieGaynor Thank you for reporting the issue, I was mostly focusing on iOS and Android. Didn't take the time to test on the web version.

So, I don't have much experience with React Native web, totally open to suggestion and insight.
