### ISSUE TITLE
Device not imported in the jest.setup.ts file

### ISSUE THREAD

**Issue by Klin-Coders** [ixartz/React-Native-Boilerplate#6]
I might be wrong but there seems to be omission of the device import in the Jest setup file in the e2e folder

the code in there is 

```
beforeAll(async () => {
  await device.launchApp();
});

beforeEach(async () => {
  await device.reloadReactNative();
});
``` 

and adding 
```import { device } from 'detox'; ```
seems to fix it

**Comment by ixartz** [comment]
Thank you for sharing the issue and thank you for contributing. I was also creating the PR: https://github.com/ixartz/React-Native-Boilerplate/pull/7 after your issue. Anyway, I'll merge your PR.

In VSCode, without the import it works perfectly. I think Detox handle correctly without the import. But, I think it's also better to be more explicit.

**Comment by ixartz** [comment]
Your fix has been merged. Thank you for your contribution.

**Comment by ixartz** [comment]
> I use vs code and Typescript flagged the issue that is why i created a PR. amazing boilerplate by the way. Thank you very much

It's very strange I don't have the issue. Anyway, it's better to be more explicit.
